name: Build Proxmox LXC Template (Debian 13 + Caddy Cloudflare)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build LXC template tarball
        run: |
          cd scripts
          ./build-lxc-template.sh
        env:
          ROOTFS: /tmp/rootfs
          TARBALL_NAME: debian-13-caddy-cloudflare_13.0-1_amd64.tar.gz

      - name: Upload template artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-13-caddy-cloudflare_13.0-1_amd64
          path: debian-13-caddy-cloudflare_13.0-1_amd64.tar.gz
